/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.myDSL.testdsl.services.TestDslGrammarAccess;
import org.myDSL.testdsl.testDsl.Expect;
import org.myDSL.testdsl.testDsl.Input;
import org.myDSL.testdsl.testDsl.Model;
import org.myDSL.testdsl.testDsl.TestCase;
import org.myDSL.testdsl.testDsl.TestDslPackage;
import org.myDSL.testdsl.testDsl.TestSuite;

@SuppressWarnings("all")
public class TestDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TestDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TestDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TestDslPackage.EXPECT:
				sequence_Expect(context, (Expect) semanticObject); 
				return; 
			case TestDslPackage.INPUT:
				sequence_Input(context, (Input) semanticObject); 
				return; 
			case TestDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case TestDslPackage.TEST_CASE:
				sequence_TestCase(context, (TestCase) semanticObject); 
				return; 
			case TestDslPackage.TEST_SUITE:
				sequence_TestSuite(context, (TestSuite) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Step returns Expect
	 *     Expect returns Expect
	 *
	 * Constraint:
	 *     (key=ID value=ID)
	 * </pre>
	 */
	protected void sequence_Expect(ISerializationContext context, Expect semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TestDslPackage.Literals.STEP__KEY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TestDslPackage.Literals.STEP__KEY));
			if (transientValues.isValueTransient(semanticObject, TestDslPackage.Literals.STEP__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TestDslPackage.Literals.STEP__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExpectAccess().getKeyIDTerminalRuleCall_1_0(), semanticObject.getKey());
		feeder.accept(grammarAccess.getExpectAccess().getValueIDTerminalRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Step returns Input
	 *     Input returns Input
	 *
	 * Constraint:
	 *     (key=ID value=STRING)
	 * </pre>
	 */
	protected void sequence_Input(ISerializationContext context, Input semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TestDslPackage.Literals.STEP__KEY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TestDslPackage.Literals.STEP__KEY));
			if (transientValues.isValueTransient(semanticObject, TestDslPackage.Literals.STEP__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TestDslPackage.Literals.STEP__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInputAccess().getKeyIDTerminalRuleCall_1_0(), semanticObject.getKey());
		feeder.accept(grammarAccess.getInputAccess().getValueSTRINGTerminalRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (name=ID testCases+=TestCase*)
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TestCase returns TestCase
	 *
	 * Constraint:
	 *     (name=ID steps+=Step*)
	 * </pre>
	 */
	protected void sequence_TestCase(ISerializationContext context, TestCase semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TestSuite returns TestSuite
	 *
	 * Constraint:
	 *     (name=ID testCases+=TestCase*)
	 * </pre>
	 */
	protected void sequence_TestSuite(ISerializationContext context, TestSuite semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
