/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.myDSL.testdsl.ui.internal.TestdslActivator;

public class TestDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TestdslActivator.getInstance().getInjector("org.myDSL.testdsl.TestDsl");
	}

}
