/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.myDSL.testdsl.ide.contentassist.antlr.internal.InternalTestDslParser;
import org.myDSL.testdsl.services.TestDslGrammarAccess;

public class TestDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TestDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TestDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStepAccess().getAlternatives(), "rule__Step__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getTestSuiteAccess().getGroup(), "rule__TestSuite__Group__0");
			builder.put(grammarAccess.getTestCaseAccess().getGroup(), "rule__TestCase__Group__0");
			builder.put(grammarAccess.getInputAccess().getGroup(), "rule__Input__Group__0");
			builder.put(grammarAccess.getExpectAccess().getGroup(), "rule__Expect__Group__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
			builder.put(grammarAccess.getModelAccess().getTestCasesAssignment_2(), "rule__Model__TestCasesAssignment_2");
			builder.put(grammarAccess.getTestSuiteAccess().getNameAssignment_1(), "rule__TestSuite__NameAssignment_1");
			builder.put(grammarAccess.getTestSuiteAccess().getTestCasesAssignment_2(), "rule__TestSuite__TestCasesAssignment_2");
			builder.put(grammarAccess.getTestCaseAccess().getNameAssignment_1(), "rule__TestCase__NameAssignment_1");
			builder.put(grammarAccess.getTestCaseAccess().getStepsAssignment_3(), "rule__TestCase__StepsAssignment_3");
			builder.put(grammarAccess.getInputAccess().getKeyAssignment_1(), "rule__Input__KeyAssignment_1");
			builder.put(grammarAccess.getInputAccess().getValueAssignment_3(), "rule__Input__ValueAssignment_3");
			builder.put(grammarAccess.getExpectAccess().getKeyAssignment_1(), "rule__Expect__KeyAssignment_1");
			builder.put(grammarAccess.getExpectAccess().getValueAssignment_3(), "rule__Expect__ValueAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TestDslGrammarAccess grammarAccess;

	@Override
	protected InternalTestDslParser createParser() {
		InternalTestDslParser result = new InternalTestDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TestDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TestDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
