/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.myDSL.testdsl.TestDslRuntimeModule;
import org.myDSL.testdsl.TestDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TestDslIdeSetup extends TestDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TestDslRuntimeModule(), new TestDslIdeModule()));
	}
	
}
