/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestDslRuntimeModule extends AbstractTestDslRuntimeModule {
}
