/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TestDslStandaloneSetup extends TestDslStandaloneSetupGenerated {

	public static void doSetup() {
		new TestDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
