/**
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.testDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.myDSL.testdsl.testDsl.Expect;
import org.myDSL.testdsl.testDsl.TestDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expect</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpectImpl extends StepImpl implements Expect
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestDslPackage.Literals.EXPECT;
  }

} //ExpectImpl
