/**
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.testDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.myDSL.testdsl.testDsl.Input;
import org.myDSL.testdsl.testDsl.TestDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Input</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InputImpl extends StepImpl implements Input
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InputImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestDslPackage.Literals.INPUT;
  }

} //InputImpl
