/**
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.testDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expect</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.myDSL.testdsl.testDsl.TestDslPackage#getExpect()
 * @model
 * @generated
 */
public interface Expect extends Step
{
} // Expect
