/**
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.testDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.myDSL.testdsl.testDsl.TestDslFactory
 * @model kind="package"
 * @generated
 */
public interface TestDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "testDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.myDSL.org/testdsl/TestDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "testDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TestDslPackage eINSTANCE = org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.myDSL.testdsl.testDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.myDSL.testdsl.testDsl.impl.ModelImpl
   * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Test Cases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TEST_CASES = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.myDSL.testdsl.testDsl.impl.TestSuiteImpl <em>Test Suite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.myDSL.testdsl.testDsl.impl.TestSuiteImpl
   * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getTestSuite()
   * @generated
   */
  int TEST_SUITE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__NAME = 0;

  /**
   * The feature id for the '<em><b>Test Cases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__TEST_CASES = 1;

  /**
   * The number of structural features of the '<em>Test Suite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.myDSL.testdsl.testDsl.impl.TestCaseImpl <em>Test Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.myDSL.testdsl.testDsl.impl.TestCaseImpl
   * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getTestCase()
   * @generated
   */
  int TEST_CASE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__STEPS = 1;

  /**
   * The number of structural features of the '<em>Test Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.myDSL.testdsl.testDsl.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.myDSL.testdsl.testDsl.impl.StepImpl
   * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getStep()
   * @generated
   */
  int STEP = 3;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__VALUE = 1;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.myDSL.testdsl.testDsl.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.myDSL.testdsl.testDsl.impl.InputImpl
   * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getInput()
   * @generated
   */
  int INPUT = 4;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__KEY = STEP__KEY;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__VALUE = STEP__VALUE;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.myDSL.testdsl.testDsl.impl.ExpectImpl <em>Expect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.myDSL.testdsl.testDsl.impl.ExpectImpl
   * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getExpect()
   * @generated
   */
  int EXPECT = 5;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECT__KEY = STEP__KEY;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECT__VALUE = STEP__VALUE;

  /**
   * The number of structural features of the '<em>Expect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECT_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.myDSL.testdsl.testDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.myDSL.testdsl.testDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.myDSL.testdsl.testDsl.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.myDSL.testdsl.testDsl.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.myDSL.testdsl.testDsl.Model#getTestCases <em>Test Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Cases</em>'.
   * @see org.myDSL.testdsl.testDsl.Model#getTestCases()
   * @see #getModel()
   * @generated
   */
  EReference getModel_TestCases();

  /**
   * Returns the meta object for class '{@link org.myDSL.testdsl.testDsl.TestSuite <em>Test Suite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Suite</em>'.
   * @see org.myDSL.testdsl.testDsl.TestSuite
   * @generated
   */
  EClass getTestSuite();

  /**
   * Returns the meta object for the attribute '{@link org.myDSL.testdsl.testDsl.TestSuite#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.myDSL.testdsl.testDsl.TestSuite#getName()
   * @see #getTestSuite()
   * @generated
   */
  EAttribute getTestSuite_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.myDSL.testdsl.testDsl.TestSuite#getTestCases <em>Test Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Cases</em>'.
   * @see org.myDSL.testdsl.testDsl.TestSuite#getTestCases()
   * @see #getTestSuite()
   * @generated
   */
  EReference getTestSuite_TestCases();

  /**
   * Returns the meta object for class '{@link org.myDSL.testdsl.testDsl.TestCase <em>Test Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Case</em>'.
   * @see org.myDSL.testdsl.testDsl.TestCase
   * @generated
   */
  EClass getTestCase();

  /**
   * Returns the meta object for the attribute '{@link org.myDSL.testdsl.testDsl.TestCase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.myDSL.testdsl.testDsl.TestCase#getName()
   * @see #getTestCase()
   * @generated
   */
  EAttribute getTestCase_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.myDSL.testdsl.testDsl.TestCase#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see org.myDSL.testdsl.testDsl.TestCase#getSteps()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_Steps();

  /**
   * Returns the meta object for class '{@link org.myDSL.testdsl.testDsl.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see org.myDSL.testdsl.testDsl.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the attribute '{@link org.myDSL.testdsl.testDsl.Step#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.myDSL.testdsl.testDsl.Step#getKey()
   * @see #getStep()
   * @generated
   */
  EAttribute getStep_Key();

  /**
   * Returns the meta object for the attribute '{@link org.myDSL.testdsl.testDsl.Step#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.myDSL.testdsl.testDsl.Step#getValue()
   * @see #getStep()
   * @generated
   */
  EAttribute getStep_Value();

  /**
   * Returns the meta object for class '{@link org.myDSL.testdsl.testDsl.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see org.myDSL.testdsl.testDsl.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for class '{@link org.myDSL.testdsl.testDsl.Expect <em>Expect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expect</em>'.
   * @see org.myDSL.testdsl.testDsl.Expect
   * @generated
   */
  EClass getExpect();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TestDslFactory getTestDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.myDSL.testdsl.testDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.myDSL.testdsl.testDsl.impl.ModelImpl
     * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Test Cases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TEST_CASES = eINSTANCE.getModel_TestCases();

    /**
     * The meta object literal for the '{@link org.myDSL.testdsl.testDsl.impl.TestSuiteImpl <em>Test Suite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.myDSL.testdsl.testDsl.impl.TestSuiteImpl
     * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getTestSuite()
     * @generated
     */
    EClass TEST_SUITE = eINSTANCE.getTestSuite();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_SUITE__NAME = eINSTANCE.getTestSuite_Name();

    /**
     * The meta object literal for the '<em><b>Test Cases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_SUITE__TEST_CASES = eINSTANCE.getTestSuite_TestCases();

    /**
     * The meta object literal for the '{@link org.myDSL.testdsl.testDsl.impl.TestCaseImpl <em>Test Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.myDSL.testdsl.testDsl.impl.TestCaseImpl
     * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getTestCase()
     * @generated
     */
    EClass TEST_CASE = eINSTANCE.getTestCase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_CASE__NAME = eINSTANCE.getTestCase_Name();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__STEPS = eINSTANCE.getTestCase_Steps();

    /**
     * The meta object literal for the '{@link org.myDSL.testdsl.testDsl.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.myDSL.testdsl.testDsl.impl.StepImpl
     * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP__KEY = eINSTANCE.getStep_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP__VALUE = eINSTANCE.getStep_Value();

    /**
     * The meta object literal for the '{@link org.myDSL.testdsl.testDsl.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.myDSL.testdsl.testDsl.impl.InputImpl
     * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '{@link org.myDSL.testdsl.testDsl.impl.ExpectImpl <em>Expect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.myDSL.testdsl.testDsl.impl.ExpectImpl
     * @see org.myDSL.testdsl.testDsl.impl.TestDslPackageImpl#getExpect()
     * @generated
     */
    EClass EXPECT = eINSTANCE.getExpect();

  }

} //TestDslPackage
