/**
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.testDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.myDSL.testdsl.testDsl.TestCase#getName <em>Name</em>}</li>
 *   <li>{@link org.myDSL.testdsl.testDsl.TestCase#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see org.myDSL.testdsl.testDsl.TestDslPackage#getTestCase()
 * @model
 * @generated
 */
public interface TestCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.myDSL.testdsl.testDsl.TestDslPackage#getTestCase_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.myDSL.testdsl.testDsl.TestCase#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link org.myDSL.testdsl.testDsl.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see org.myDSL.testdsl.testDsl.TestDslPackage#getTestCase_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // TestCase
