/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.myDSL.testdsl.ui.internal.TestdslActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TestDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TestdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TestdslActivator activator = TestdslActivator.getInstance();
		return activator != null ? activator.getInjector(TestdslActivator.ORG_MYDSL_TESTDSL_TESTDSL) : null;
	}

}
