/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TestDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/myDSL/testdsl/parser/antlr/internal/InternalTestDsl.tokens");
	}
}
