/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.myDSL.testdsl.parser.antlr.internal.InternalTestDslParser;
import org.myDSL.testdsl.services.TestDslGrammarAccess;

public class TestDslParser extends AbstractAntlrParser {

	@Inject
	private TestDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTestDslParser createParser(XtextTokenStream stream) {
		return new InternalTestDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TestDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TestDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
