/*
 * generated by Xtext 2.32.0
 */
package org.myDSL.testdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTestDslScopeProvider extends DelegatingScopeProvider {
}
